Product.create(title: 'Chorizo')
Product.create(title: 'Cogumelos')
Product.create(title: 'Misto')
Product.create(title: 'Marguerita')
Product.create(title: 'Banana com Nutella')
Product.create(title: 'Nutella')
Product.create(title: 'Romeo e Julieta')
Product.create(title: 'Banana com Leite Condensado')
